# Generated by Django 4.2.2 on 2023-06-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=100)),
                ('expire', models.DateField()),
            ],
        ),
    ]
